  
SELECT TOP 20 *
FROM customer_data;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT GENDER,SUM(PURCHASED_AMOUNT)[TOTAL REVENUE]
FROM CUSTOMER_DATA
GROUP BY GENDER 

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,discount_applied
FROM customer_data
where discount_applied = 'Yes' and purchased_amount > (select avg(purchased_amount)from customer_data)

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
	   item_purchased,
	   AVG(review_rating) AS average_product_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

select * from customer_data
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchased_amount)
from customer_data
where shipping_type in ('standard','express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue --between subscribers and non-subscribers.
select subscription_status,avg(purchased_amount) as 'avg spend',sum(purchased_amount) as 'total_revenue',count(customer_id) as total_customer
from customer_data
group by subscription_status 
order by total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,count(case when discount_applied = 'yes' then 1 end)*100 / count(*) as Discount_rate
from customer_data
group by item_purchased
order by Discount_rate desc;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as
( select case when previous_purchases = 1 then 'New'
			  when previous_purchases between 2 and 10 then 'Returning'
			  else 'loyal'
			  end as customer_segment
from customer_data)

select customer_segment,count(*) as number_of_customer
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
WITH product_count AS
(
	SELECT
		category,
		item_purchased,
		COUNT(*) AS purchase_count
	FROM customer_data
	GROUP BY category, item_purchased
),

product_rank AS
(
	SELECT *,
		   DENSE_RANK() OVER
		   (
			   PARTITION BY category
				ORDER BY purchase_count DESC
		   ) AS rnk
	FROM product_count
)

SELECT
	category,
	item_purchased,
	purchase_count
FROM product_rank
WHERE rnk <= 2

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as Repeat_Buyers
from customer_data
where previous_purchases > 5
group by subscription_status
order by Repeat_Buyers desc

--Q10. What is the revenue contribution of each age group? 
select age_group , sum(purchased_amount) as Revenue_Contribution
from customer_data
group by age_group
order by Revenue_Contribution desc